### ISSUE TITLE
My thoughts

### ISSUE THREAD

**Issue by notxcain** [krasserm/akka-stream-eventsourcing#1]
That is close to something I work on. I just want to share my thoughts on what could be improved.
To be able to make response depend on request I've found it very useful to encode aggregate operations using GADTs.
e.g.
```scala
sealed trait KeyValueStoreOp[A]
case class Set(key: String, value: String) extends KeyValueStoreOp[Unit]
case class Get(key: String) extends KeyValueStoreOp[Option[String]]
```
Then `RequestHandler` becomes a natural transformation (`~>`)
```scala
type Out[E, S, A] = (Seq[E], S => A)
type In[S, Req[_], A] = (S, Req[A])
type RequestHandler[S, E, Req[_]] = In[S, Req, ?] ~> Out[E, S, ?]
```
Also,
sometimes there are impossible pairs of `(Event, State)`.
Let's say you have an `Order` aggregate. 
It's state has type `Option[OrderState]` with `None` being initial state.
You can have `OrderSubmitted` event only once, and only when the state is `None`
so when you implement `EventHandler` you would have to handle a case 
`(Some(state), e: OrderSubmitted)` and to be pure and total I use this type for `EventHandler`
```scala
type EventHandler[S, E] = (S, E) => Folded[S]

sealed trait Folded[+A]
case class Next[+A](a: A) extends Folded[A]
case class Impossible extends Folded[Nothing]
```
then you can handle the above case like that
```
case (Some(state), e: OrderSubmitted) => Impossible
```
Of course later the runtime throws when it sees `Impossible`, but it is the end of the world so it's fine.

**Comment by krasserm** [comment]
Thanks @notxcain for sharing your thoughts. I definitely see the advantage of encoding response to request type dependencies but I don't see how I can leverage that in a context (i.e. graph stage) with fixed input and output ports types. Can you please elaborate?

Your second proposal seems to be a step towards supporting an event handling state machine that allows applications to return a new event handler in addition to updated state with support for detecting invalid (or impossible) transitions. Behavior changes during event handling is definitely something I'd like to add in upcoming versions.

**Comment by jbgi** [comment]
> so when you implement EventHandler you would have to handle a case
(Some(state), e: OrderSubmitted) and to be pure and total I use this type for EventHandler

You can also simply handle the case as
`(_ ,  e: OrderSubmitted)` since you trust your aggregate to not emit `OrderSubmitted` event for other state than none.

**Comment by notxcain** [comment]
@krasserm 
To be able to use this encoding in streams one could use continuation passing style (which is very close to how Akka Typed works with its `replyTo: ActorRef[Res]`).

```scala
sealed abstract class Operation[Req[_]] {
  type Res
  def request: Req[Res]
  def complete(res: Try[Res]): Unit
}
object Operation {
  def apply[Req[_], Res0](request0: Req[Res], complete0: Try[Res] => Unit): Operation[Req] =
    new Operation[Req] {
      type Res = Res0
      def request: Req[Res] = request0
      def complete(res: Try[Res]): Unit = complete0(res)
    }
}
```

So instead of `flow: Flow[Req, Res, _]` you'll get `flow: Flow[Operation[Req], Unit, _]`.
Then somewhere at the edge of your app you use it like this

```scala
val eventsourced: Flow[Operation[KeyValuesStoreOp], Unit, _] = ...

val queue = 
  Source
    .queue[Operation[KeyValueStoreOp]]
    .viaMat(eventsourced)(Keep.left)
    .toMat(Sink.ignore)(Keep.left)
    .run

def runOp[A](op: KeyValueStoreOp[A]): Future[A] = {
  val promise = Promise[A]
  queue.offer(Operation(op, promise.complete)).flatMap(_ => promise.future)
}

val setAndGetFoo: Future[Option[String]] = 
  for {
    _ <- runOp(Set("foo", "bar"))
    foo <- runOp(Get("foo"))
  } yield foo
```

@jbgi
Actually I don't trust my aggregates this much, I trust types and prefer to rely on the compiler when possible 🤓 
It's better to crash during runtime that silently ignore this programmer error.
Good thing is that runtime performs fold before persisting the events,
so there would be much smaller chance to corrupt event log.

**Comment by krasserm** [comment]
@notxcain what you're doing is degenerating the event-sourcing graph stage to an asynchronous boundary and by-passing back-pressure. This is far from idiomatic Akka Streams usage, if not abuse. Instead of driving the request and event handler "at the edge of your app" it is the event- sourcing graph stage itself that is the driver/interpreter of the request and event handler and that does the IO with its stage ports. 

It would be interesting though to see how your approach would fit into a purely functional approach to streaming like FS2, for example, but this is probably out of this ticket's scope.

**Comment by notxcain** [comment]
@krasserm 
> what you're doing is degenerating the event-sourcing graph stage to an asynchronous boundary and by-passing back-pressure. This is far from idiomatic Akka Streams usage, if not abuse. 
 
There is no back-pressure bypassing. `SourceQueue#offer` respects back-pressure. But I agree it is not idiomatic.

> Instead of driving the request and event handler "at the edge of your app" it is the event- sourcing graph stage itself that is the driver/interpreter of the request and event handler and that does the IO with its stage ports.

Ah, I understood what I get wrong. Your interface is more generic. What you propose is like `Flow[HttpRequest, HttpResponse, _]`, but underlying implementation could leverage GADT based encoding of operations, and provide HTTP decoders and encoders.

**Comment by krasserm** [comment]
> There is no back-pressure bypassing. `SourceQueue#offer` respects back-pressure

Yes, but you introduced a completely new mechanism to notify response consumers: via `complete`. Response consumers should instead be downstream consumers in the pipeline but in your example it's `Sink.ignore` which doesn't back-pressure.

**Comment by krasserm** [comment]
Closing this ticket now. Support for event handling state machines is now covered by #3. @notxcain This can be extended with an `Impossible` handler result if needed (in addition to `Update` and `Become`). Thanks again for the inspiration!
