### ISSUE TITLE
Serializer error at import

### ISSUE THREAD

**Issue by Allysh0w** [krasserm/akka-stream-eventsourcing#15]
I'm trying to compile the project and I received an error at import in EmittedSerializer and PayloadSerializer class at import
`import com.github.krasserm.ases.serializer.PayloadFormatOuterClass.PayloadFormat`  
and 
`import com.github.krasserm.ases.serializer.EmittedFormatOuterClass.EmittedFormat`
Why theses classes are not defined in package?

**Comment by krasserm** [comment]
These are protobuf-generated classes that are automatically generated by an sbt plugin when running `sbt compile` or `sbt test::compile`. If you're using your IDE to compile the project please make sure these sbt targets are used. If the error persists even with `sbt test::compile` please re-open this issue.
