### ISSUE TITLE
Behavior changes for request and event handlers

### ISSUE THREAD

**Issue by krasserm** [krasserm/akka-stream-eventsourcing#3]
Allow handlers to optionally return a new handler for changing behavior across handler invocations. This can be used to implement request and event handling state machines. Given

```scala
object EventHandler {
  type EventHandler[S, E] = (S, E) => EventHandlerResult[S, E]

  sealed trait EventHandlerResult[S, E]
  case class Update[S](s: S) extends EventHandlerResult[S, Nothing]
  case class UpdateAndThen[S, E](s: S, eh: EventHandler[S, E]) extends EventHandlerResult[S, E]

  def update[S, E](s: S): EventHandlerResult[S, E] =
    Update(s).asInstanceOf[EventHandlerResult[S, E]]

  def updateAndThen[S, E](s: S, eh: EventHandler[S, E]): EventHandlerResult[S, E] =
    UpdateAndThen(s, eh)
```

event handlers can be defined like in the following example:

```scala
import EventHandler._

case class Changed(delta: Int) // example event

def h1: EventHandler[Int, Changed] = {
  case (s, Changed(0)) => updateAndThen(s, h2)
  case (s, Changed(d)) => update(s + d)
}

def h2: EventHandler[Int, Changed] = {
  case (s, Changed(0)) => updateAndThen(s, h1)
  case (s, Changed(d)) => update(s - d)
}
```

The `EventSourcing` graph stage pattern-matches `EventHandlerResult`s for updating current state and optionally updating current handler behavior.

**Comment by krasserm** [comment]
A similar approach is made for request handlers:

```scala
object RequestHandler {
  type RequestHandler[S, E, REQ, RES] = (S, REQ) => RequestHandlerResult[S, E, REQ, RES]

  sealed trait RequestHandlerResult[S, E, REQ, RES]

  case class Respond[RES](res: RES)
    extends RequestHandlerResult[Nothing, Nothing, Nothing, RES]

  case class RespondAndThen[S, E, REQ, RES](res: RES, rh: RequestHandler[S, E, REQ, RES])
    extends RequestHandlerResult[S, E, REQ, RES]

  case class Emit[S, E, RES](es: Seq[E], res: S => RES)
    extends RequestHandlerResult[S, E, Nothing, RES]

  case class EmitAndThen[S, E, REQ, RES](es: Seq[E], res: S => RES, rh: RequestHandler[S, E, REQ, RES])
    extends RequestHandlerResult[S, E, REQ, RES]

  def respond[S, E, REQ, RES](res: RES): RequestHandlerResult[S, E, REQ, RES] =
    Respond(res).asInstanceOf[RequestHandlerResult[S, E, REQ, RES]]

  def respondAndThen[S, E, REQ, RES](res: RES, rh: RequestHandler[S, E, REQ, RES]): RequestHandlerResult[S, E, REQ, RES] =
    RespondAndThen(res, rh)

  def emit[S, E, REQ, RES](es: Seq[E], res: S => RES): RequestHandlerResult[S, E, REQ, RES] =
    Emit(es, res).asInstanceOf[RequestHandlerResult[S, E, REQ, RES]]

  def emitAndThen[S, E, REQ, RES](es: Seq[E], res: S => RES, rh: RequestHandler[S, E, REQ, RES]): RequestHandlerResult[S, E, REQ, RES] =
    EmitAndThen(es, res, rh)
}
```

**Comment by jbgi** [comment]
I am skeptical about the need to support switching of handlers.

From a technical pov it complicates the model for very little: the types are still the same before and after switching, so type-safety is not really improved. It does add a bit of convenience but only if one does not persist state. As soon as you want snapshots (ie. not replaying all the events at startup) then you still need the logic of deriving the right handler from the state, so nothing is gained, worse: this logic might be duplicated.

Also from a ddd pov I have the feeling that many use-cases of this feature would be better served by creating a new aggregate (of different type).

**Comment by krasserm** [comment]
The switching handler API will co-exist with the initially proposed simpler handler API so users won't be forced to use the switching API. One could even implement the simpler API in terms of the switching API ... 

I agree that many applications probably won't need the switching API and will only use the simpler API. But there are use cases where a switching API makes writing handlers easier. For example, I worked on a distributed job management application where jobs switch to different "phases" depending on the job progress. Using a separate aggregate for each phase would have complicated our model and application logic significantly. 

Also, we didn't have to use snapshots here as each job aggregate has an event history with no more that a few hundred events which can be replayed within milliseconds. But the general problem with snapshots remains and the documentation should warn the user about the fact (as done in Eventuate's [Behavior changes](http://rbmhtechnology.github.io/eventuate/reference/event-sourcing.html#behavior-changes) section, for example, or label the switching API as an *expert feature*).

**Comment by patriknw** [comment]
I think that a simpler way is to have a `S => RequestHandler`, i.e. the current request handler is always chosen based on the current state. That makes replay easier because you don't have to think about switching behavior, you only apply the events to the state and you end up with the "right" request handler for that state. Even more important is that it fits better with snapshots, because you must anyway encode current request handler in the snapshot state and restore that when consuming the snapshot.

**Comment by patriknw** [comment]
and I don't think there is any need for switching event handlers

**Comment by krasserm** [comment]
I like the `S => RequestHandler` idea. If I see it correctly, it's also a sufficient basis for building an equivalent to `PersistentFSM` on top of it, even if we don't have event handler switching.

> and I don't think there is any need for switching event handlers

Event handler switching can be more convenient in some cases especially if different lifecycle phases of an aggregate use different events (see [previous comment](https://github.com/krasserm/akka-stream-eventsourcing/issues/3#issuecomment-306438737)). 

Is it that you just don't see a use case for it at the moment or is there another reason why you think they shouldn't be there?

**Comment by krasserm** [comment]
> you must anyway encode current request handler in the snapshot state and restore that when consuming the snapshot

So you want to leave it to the application how to encode request handlers? For example, using handler ids and storing them in the snapshot?

**Comment by patriknw** [comment]
> Event handler switching can be more convenient

for the rare cases you can do the event handler switching in the event handler itself `(S, E) => S`, since the state is there also

> So you want to leave it to the application how to encode request handlers? For example, using handler ids and storing them in the snapshot?

With your original proposal that is what they would have to do. With my proposal there is no need for that, since the choice is always based on the state, i.e. the state can be used as is as the snapshot without having to think (and forget) about having an extra encoding for which command handler to use.

**Comment by krasserm** [comment]
Now I'm confused: `S => RequestHandler` is a user-defined function that returns a request handler based on current state (if the `EventSourcing` stage receives a request from upstream). So the request handler is a function of the state value, isn't it?

**Comment by krasserm** [comment]
> for the rare cases you can do the event handler switching in the event handler itself `(S, E) => S`, since the state is there also

yes, but this requires the event handler to be stateful i.e. state managed by the application in contrast to state managed within the graph stage.

**Comment by patriknw** [comment]
> Now I'm confused: S => RequestHandler is a user-defined function that returns a request handler based on current state (if the EventSourcing stage receives a request from upstream). So the request handler is a function of the state value, isn't it?

yes

> but this requires the event handler to be stateful

no, your example would be:

```
case class State(count: Int, increment: Boolean)

def h: EventHandler[State, Changed] = {
  case (s, Changed(0)) => s.copy(increment = !s.increment)
  case (s, Changed(d)) => 
    if (s.increment) s.copy(count = s.count + d)
    else s.copy(count = s.count - d)
}
```

(rather artifical example because such a thing would be better with events `Incremented` and `Decremented`)

**Comment by krasserm** [comment]
>> Now I'm confused: S => RequestHandler is a user-defined function that returns a request handler based on current state (if the EventSourcing stage receives a request from upstream). So the request handler is a function of the state value, isn't it?

> yes

fine, but then state `S` somehow encodes which request handler to use.

**Comment by krasserm** [comment]
Regarding switching event handlers: what if we follow an approach symmetric to switching request handlers i.e. `S => EventHandler`? It is then trivial to additionally support the initially proposed event handler approach i.e. `(S, E) => S`.

**Comment by patriknw** [comment]
> Regarding switching event handlers

that's fine if you think it's worth the additional complexity (not only impl, but also conceptually for user)

**Comment by krasserm** [comment]
They can use the simpler API if they want and don't need to care about `S => EventHandler` (the same is true for the request handler either if users only want to use a single request handler). Also, as a user, I'd find it more surprising if there is a request handler factory `S => RequestHandler` but no event handler factory `S => EventHandler` i.e. I find this symmetry conceptually cleaner.

**Comment by krasserm** [comment]
@patriknw @jbgi I just implemented and pushed what we've discussed so far: https://github.com/krasserm/akka-stream-eventsourcing/commit/3f52c275878b1e64ef9eb475d3c6ae94ae22c4ec. Old API is preserved except that the request handler result type has been changed so that it can either be `Respond` or `Emit` only. Would be great if you could take a look.
