### ISSUE TITLE
Event logging protocol extensions

### ISSUE THREAD

**Issue by krasserm** [krasserm/akka-stream-eventsourcing#5]
So far event logs were modeled as `Flow[E, Delivery[E], _]` and `EventSourcing` stages as `BidiFlow[REQ, E, Delivery[E], RES, _]` where `E` is the type of a domain event. This is not sufficient for real-world use cases. Further event metadata are required: 

- Events emitted by an `EventSourcing` stage must contain the id of the emitting stage (`emitterId`). This is needed, for example, by consumers on the query side of a CQRS application to distinguish emitters when consuming events from an aggregated or shared event log. This is also a prerequisite for creating snapshots of `EventSourcing` state on the query side by re-using event handlers.
- Events emitted by an event log must additionally contain the sequence number of the written event. Sequence numbers are required to track event processing progress, for example.

For these reasons, the current implementation should be extended to use

```scala
Flow[Emitted[E], Delivery[Durable[E]], _]
```

as type for event logs and 

```scala
BidiFlow[REQ, Emitted[E], Delivery[Durable[E]], RES, _]
```

as type for `EventSourcing` stages where `Emitted` and `Durable` are defined as:

```scala
/**
  * Metadata and container of an event emitted by an `EventSourcing` stage.
  *
  * @param event Emitted event.
  * @param emitterId Id of the event emitter.
  * @param emissionUuid Emission id generated by the event emitter.
  * @tparam A Event type
  */
case class Emitted[+A](event: A, emitterId: String, emissionUuid: String)

/**
  * Metadata and container of a durable event emitted by an event log or source.
  *
  * @param event Durable event.
  * @param emitterId Id of the initial event emitter.
  * @param emissionUuid Emission id generated by the initial event emitter.
  * @param sequenceNr Sequence number of the durable event.
  * @tparam A Event type
  */
case class Durable[+A](event: A, emitterId: String, emissionUuid: String, sequenceNr: Long)
```

**Comment by jbgi** [comment]
Why not using only a single case class,
`case class Emitted[+A](event: A, emitterId: String, sequenceNr: Long)`
With the sequenceNr being relative to the emmiterId. The EventSourcing can (should?) keep track of the `sequenceNr`.

**Comment by krasserm** [comment]
With client-assigned sequence numbers [event collaboration](https://github.com/krasserm/akka-stream-eventsourcing#request-processor-collaboration-microservices) would require members of a collaboration group have distributed agreement on these numbers before writing events to a shared event log. A much more efficient way is to let the shared event log assign the sequence numbers i.e. clients use the shared event log for distributed agreement. But this is nothing else than server-assigned sequence numbers, hence the difference between `Emitted` and `Durable`.

Akka Persistence (with client- i.e. `PersistentActor`-assigned sequence numbers) is a special case as each `PersistentActor` has its own private event log. But this approach has limitations, especially when used it in context of CQRS and event collaboration.

**Comment by jbgi** [comment]
I see. There is definitely benefits for this relaxed consistency model (that required CRDT / vector clocks), but I'd like the API to also support the traditional (simpler) ES model where strong causality of the (unique) event log is ensured by, and only by, the `RequestHandler`. Will it still be possible?
(because not everyone has scalability issues that mandate usage of more advance architectures like event collaboration/CRDT)

**Comment by krasserm** [comment]
> There is definitely benefits for this relaxed consistency model (that required CRDT / vector clocks)

This has nothing to do with relaxed consistency. In the [collaboration example](https://github.com/krasserm/akka-stream-eventsourcing#request-processor-collaboration-microservices), all group members see events in the same order (which gives you linearizability) because the underlying Kafka topic partition provides total order (as mentioned in the text). No relaxed consistency, vector clocks etc. here.

> but I'd like the API to also support the traditional (simpler) ES model where strong causality of the (unique) event log is ensured by, and only by, the `RequestHandler`

A request handler alone cannot provide total storage order, it is the event log that must give you these guarantees.

> Will it still be possible?

Everything you can do with `PersistentActor`s you can also do with `EventSourcing` stages and `AkkaPersistenceEventLog`. So the answer is yes.

> (because not everyone has scalability issues that mandate usage of more advance architectures like event collaboration/CRDT)

Please don't confuse event collaboration with CRDTs or relaxed consistency: event collaboration only means exchange of events among collaborators. The ordering guarantees of the underlying event log determines the order of events seen by collaborators. Kafka topic partitions provide a total order broadcast, local Eventuate event logs also provide a total order broadcast, distributed Eventuate event logs provide a causal order broadcast. Akka Persistence event logs cannot be used for collaboration (except within a JVM, an extension that will come later)

Operation-based CRDTs **may** use event collaboration as basis for operation dissemination, the minimum requirement is a reliable, causal order broadcast but, of course, they also work with a total order broadcast.

It is **not** the goal of this project to re-implement Eventuate, instead applications should have the option to use a globally replicated Eventuate event log if causal order is sufficient and multi-datacenter replication is a requirement. If stronger consistency is needed they should use the event logs already implemented in this project (Kafka and Akka Persistence).
